SELECT INDEX_OWNER,
       INDEX_NAME,
       TABLE_OWNER,
       TABLE_NAME,
       COLUMN_NAME,
       COLUMN_POSITION,
       COLUMN_LENGTH,
       CHAR_LENGTH,
       DESCEND
FROM ALL_IND_COLUMNS  
WHERE INDEX_OWNER = @OWNER
